### ISSUE TITLE
Instructions to use dataset

### ISSUE THREAD

**Issue by imprs** [jonasjuhlern/REIGATO#1]
Hi @jonasjuhler,
Thanks for sharing the code. Is it possible for you to share the dataset as well? 

Thanks!

**Comment by imprs** [comment]
Never mind. Found it in the[ LSTM-AnomalyDetection](https://github.com/jonasjuhler/LSTM-AnomalyDetection/tree/master) repo. Thanks!

**Comment by imprs** [comment]
Hi @jonasjuhler,

If you have time, could you provide some instructions on how to generate dataset from the other repo to use with these notebooks?

**Comment by jonasjuhler** [comment]
I think that the actual data writing was accidentally left out of repo, so I don't think it actually exists anywhere. This is the link for the Google Drive folder with it: https://drive.google.com/file/d/1GbKQMJU0Yidfh9MKMbA9ORMZ-_50TQ15/view?usp=sharing

**Comment by imprs** [comment]
Totally forgot about this. Thanks a lot @jonasjuhler!
